apiVersion: v1
kind: Namespace
metadata:
  name: services

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuck-jokes
  namespace: services
  labels:
    app: chuck-jokes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chuck-jokes
  template:
    metadata:
      labels:
        app: chuck-jokes
    spec:
      containers:
        - name: chuck-jokes
          image: kubeshop/chuck-jokes:latest
          ports:
            - containerPort: 8881
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: chuck-jokes
  namespace: services
spec:
  selector:
    app: chuck-jokes
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
