name: "Linting pr"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      
jobs:
  prlint:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}